Feature/9 votos panel
Full-Tortuga/decide-full-tortuga-almacenamiento pull request #31
Opened 2021-12-27 19:59 UTC by NoSoyDani

Añade al panel de control la funcionalidad necesaria para mostrar los resultados obtenidos de una votación en la sección "Votos", introduciendo la id de la votación en la URL.

2022-01-02 09:26 UTC, manmunesp12 approved these changes
Funcionalidad comprobada, panel de voto implementado correctamente.

2022-01-02 09:44 UTC, Javitoox requested changes
Cambios requeridos:
- Obtención de datos en tiempo real.
- La obtención de los votos se debe hacer sin modificar la url.
- Añadir información adicional a los votos.

2022-01-03 19:23 UTC, NoSoyDani commented
Se ha implementado lo solicitado en la última request change.

2022-01-05 01:45 UTC, Javitoox submitted a review, later dismissed
Cambios requeridos que quedan por hacer:

Añadir información adicional a los votos.

Además al revisar la información mostrada, la funcionalidad requería mostrar los votos. Actualmente solo se puede ver información genérica de la votación y no se puede ver información acerca de los votos. Para ello se debería de modificar el backend.

2022-01-05 11:14 UTC, Javitoox commented
La funcionalidad extra requerida es referente al censo, ya que actualidad la vista de votos muestra la misma información que el propio panel de administración de Django. Para la vista de votaciones se implementó en su momento información extra relacionada con el censo tal y como requería el incremento, en caso contrario el incremento no sería notable. Por lo tanto, teniendo en cuenta que la vista de votas es una copia de la vista de votaciones y no añade ninguna información nueva, se requiere mostrar algún tipo de información extra relacionada con el censo, ya que esto es fácilmente modificable en el backend de decide y no pone en entredicho la privacidad del usuario, ya que es información relacionada con el censo y dicho censo con tiene el id de la votación a la que pertenece y el id del usuario.

2022-01-05 11:15 UTC, dancasnar1 approved these changes
Se ha comprobado el correcto funcionamiento de la funcionalidad.

2022-01-05 11:16 UTC, Javitoox requested changes, later dismissed
Se requiere añadir lo comentado anteriormente. Actualmente no hay ningún incremento de la funcionalidad al ser una copia de la vista de votaciones.

2022-01-05 11:21 UTC, merged

2022-01-05 11:38 UTC, Javitoox commented
No hay ninguna funcionalidad añadida y se ha aceptado la pull request quitando mi revisión sin previo aviso. Tal y como bien se describe aquí: 
![image](https://user-images.githubusercontent.com/55922195/148211187-446855ee-1f94-451a-b4da-d9709b5499fc.png)
El incremento es añadir nueva información, ya que los otros incrementos de tiempo real y otras funcionalidades ya los había implementado anteriormente y solo ha sido replicar lo mismo en esta tarea. La descripción de la tarea debía haber sido redactada siguiendo la imagen anterior, ya que es la descripción propuesta por la asignatura.

En la API no hay nada modificado y tal y como se puede ver en la vista de votos se muestra exactamente lo mismo que en la vista de votaciones previamente implementada, por lo que esta vista ha sido un copia y pega de la vista de votaciones y sin añadir nada nuevo.

No se requería modificar ningún dato privado de los votos, solo datos del censo tal y como se muestra en la descripción anterior y esto se hacía fácilmente modificando un método en el backend, al igual que ha sido modificado para la vista de votaciones. Esta tarea llevaba desde el primer día que se empezó el proyecto y hubiera dado tiempo de sobra.

Además, ha sido esta pull request ha sido aceptada sin el consentimiento de la mayoría del grupo.